# Generated by Django 2.1.3 on 2018-12-01 21:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_descriptive_name', models.CharField(max_length=256)),
                ('customer_descriptive_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_criteria_id', models.BigIntegerField(null=True)),
                ('country_criteria_id', models.BigIntegerField(null=True)),
                ('metro_criteria_id', models.BigIntegerField(null=True)),
                ('most_specific_criteria_id', models.BigIntegerField(null=True)),
                ('region_criteria_id', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
                ('device', models.CharField(max_length=256)),
                ('is_targeting_location', models.BooleanField(default=False)),
                ('location_type', models.CharField(max_length=256)),
                ('average_position', models.FloatField(default=0.0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.FloatField(default=0.0)),
                ('conversion_value', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('impressions', models.IntegerField(default=0)),
                ('interactions', models.IntegerField(default=0)),
                ('interaction_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=8)),
                ('video_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=256)),
                ('campaign_status', models.CharField(max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign'),
        ),
    ]
