# Generated by Django 2.1.3 on 2018-12-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181201_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='uuid',
        ),
    ]
